export const ADD_USER_TO_CONTEXT = 'ADD_USER_TO_CONTEXT';
export const AUTH_ERROR = 'AUTH_ERROR';
export const DE_AUTHENTICATE = 'DE_AUTHENTICATE';

export const TOGGLE_SIDE_MENU = 'TOGGLE_SIDE_MENU';
export const CLOSE_SIDE_MENU = 'CLOSE_SIDE_MENU';

export const TOGGLE_DRAWER = 'TOGGLE_DRAWER';
export const CLOSE_DRAWER = 'CLOSE_DRAWER';

export const SHOW_LOADER = 'SHOW_LOADER';
export const HIDE_LOADER = 'HIDE_LOADER';